import { Providers } from "@/app/components/client/Providers"
import { WeatherProvider } from "@/app/contexts/weatherContext"

export const metadata = {
    title: "Weather App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <WeatherProvider>
                    <Providers>{children}</Providers>
                </WeatherProvider>
            </body>
        </html>
    )
}
